[initWindowConfig]
#emulatorName="MuMu模拟器"
#emulatorGameName=" - MuMu模拟器"
emulatorGameName="雷电模拟器"
emulatorPath="D:\\application\\mumu\\emulator\\nemu\\EmulatorShell\\NemuLauncher.exe"
emulatorStartTime=20
retry=3
#startPos=[-1800,400]
startPos=[10,10]
takeDrag=1
#antiDetect=True

#Do not change the size of window!!! other wise image recognze will not work!!!
size=[720, 1380]
#分辨率为3840*2160的窗口大小配置
dpi="3840_2160"
#分辨率为2560*1440的窗口大小配置
#dpi="2560_1440"

#选项"正确""错误"配置
#flag="True"
flag="False"
#图标公共路径
publicpath="./images/OperationIcon/VisionVeraIcon/"

[time]
#gameStartTime=1
gameWatingTime=1
#ocr间隔时间
ocrDelayTime=0.8
#鼠标点击间隔时间
clickDelayTime=0.8
#延时
retryGapTime=0.8


[log]
level="INFO"
path="./log/all.log"

[img]
screenShotsPath = "./images/ScreenShots/"


[item]
url="https://planner.penguin-stats.io/"

[publicpath]

[buttons]
#correctOption="./images/OperationIcon/VisionVeraIcon/3840_2160/correctOption.png"
#errorOption="./images/OperationIcon/VisionVeraIcon/3840_2160/errorOption.png"
#commitAnswer="./images/OperationIcon/VisionVeraIcon/3840_2160/commitAnswer.png"
#nextQuestion="./images/OperationIcon/VisionVeraIcon/3840_2160/nextQuestion.png"
#errorRateMax="./images/OperationIcon/VisionVeraIcon/3840_2160/errorRateMax.png"
#trueOrFlaseQuestion="./images/OperationIcon/VisionVeraIcon/3840_2160/trueOrFlaseQuestion.png"
correctOption="correctOption.png"
errorOption="errorOption.png"
commitAnswer="commitAnswer.png"
nextQuestion="nextQuestion.png"
errorRateMax="errorRateMax.png"
trueOrFlaseQuestion="trueOrFlaseQuestion.png"

#startOperation="./images/OperationIcon/startOperation.png"
#startOperationInOperatorView="./images/OperationIcon/starOperationInOperatorView.png"
#operationEnd="./images/OperationIcon/operationEnd.png"
#uploadingData="./images/OperationIcon/upLoadingData.png"
#arkNightsApp="./images/OperationIcon/arkNightsApp.png"
#homePage_WatingForWeakup="./images/OperationIcon/homePage_WatingForWeakup.png"
#closePost="./images/OperationIcon/closePost.png"
#friendPage="./images/OperationIcon/homePage_friend.png"
#friendList="./images/OperationIcon/friendFriendList.png"
#visitFriend="./images/OperationIcon/visitFriend.png"
#visitFriendNext="./images/OperationIcon/visitFriendNext.png"
#navigate="./images/OperationIcon/navigate.png"
#navigateHome="./images/OperationIcon/navigateHome.png"
#store="./images/OperationIcon/store.png"
#storeCredit="./images/OperationIcon/storeCredit.png"
#storeCreditItem="./images/OperationIcon/storeCreditItem.png"
#storeCreditItemBuy="./images/OperationIcon/storeCreditItemBuy.png"
#task="./images/OperationIcon/task.png"
#taskCollectAll="./images/OperationIcon/taskCollectAll.png"
#base="./images/OperationIcon/base.png"
#baseRing="./images/OperationIcon/baseRing.png"
#baseTodoList="./images/OperationIcon/baseTodoList.png"
#collectStoreCredit="./images/OperationIcon/collectStoreCredit.png"
#terminal="./images/OperationIcon/terminal.png"
#eliminateOperation="./images/OperationIcon/eliminateOperation.png"
#eliminateFinish="./images/OperationIcon/eliminateFinish.png"
#takeFuckingDrug="./images/OperationIcon/takeFuckingDrug.png"